on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install changelog parser
        run: yarn
      - name: Get Changelog Entry
        id: changelog_entry
        run: node scripts/release.js
        env:
          PACKAGES: core, react
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release if does not exist
        run: echo "release this"
        if: ${{ steps.changelog_reader.outputs.already_released == false }} 

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: ${{ steps.changelog_reader.outputs.log_entry }} # This pulls from the GET CHANGELOG ENTRY step above, referencing it's ID to get its outputs object, which include a `log_entry`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          draft: false
#          prerelease: false

#      - name: npm publish
#        run: |
#          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
#          cd core
#          npm publish
#          cd ..
#          cd react
#          npm publish
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - name: Print the entry
#        run: |
#          echo "${{ steps.changelog_entry.outputs.title }}"
#          echo "${{ steps.changelog_entry.outputs.version }}"
#          echo "${{ steps.changelog_entry.outputs.description }}"

