on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install changelog parser
        run: yarn
      - name: Get Changelog Entry
        id: changelog_entry
        run: node scripts/release.js
        env:
          PACKAGES: core, react
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print the entry
        run: |
          echo "${{ steps.changelog_entry.outputs.title }}"
          echo "${{ steps.changelog_entry.outputs.version }}"
          echo "${{ steps.changelog_entry.outputs.description }}"
          echo "${{ steps.changelog_entry.outputs.unreleased }}"

      - name: Create Release
        id: create_release
        if: ${{ steps.changelog_entry.outputs.unreleased == 'true' }} 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.changelog_entry.outputs.version }}"
          release_name: Release v${{ steps.changelog_entry.outputs.version }}
          body: "${{ steps.changelog_entry.outputs.description }}"
          draft: false
          prerelease: false

      - name: npm publish
#        if: ${{ steps.changelog_entry.outputs.unreleased == 'true' }} 
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          cd core
          npm publish --tag v${{ steps.changelog_entry.outputs.version }}
          cd ..
          cd react
          npm publish --tag v${{ steps.changelog_entry.outputs.version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
