on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Get Changelog Entry
        id: changelog_entry
        run: node scripts/release.js
        env:
          PACKAGES: core, react
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print the entry
        run: |
          echo "${{ steps.changelog_entry.outputs.title }}"
          echo "${{ steps.changelog_entry.outputs.version }}"
          echo "${{ steps.changelog_entry.outputs.description }}"
          echo "${{ steps.changelog_entry.outputs.unreleased }}"

      - name: set package registry and npm token
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

      - name: publish core package
        if: ${{ steps.changelog_entry.outputs.unreleased == 'true' }} 
        run: |
          cd core
          yarn
          npm publish
      - name: publish react package
        if: ${{ steps.changelog_entry.outputs.unreleased == 'true' }} 
        run: |
          cd react
          yarn
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Github Release
        id: create_release
        if: ${{ steps.changelog_entry.outputs.unreleased == 'true' }} 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.changelog_entry.outputs.version }}"
          release_name: Release v${{ steps.changelog_entry.outputs.version }}
          body: |
            ${{ steps.changelog_entry.outputs.description }}

            ### Artifacts
            - [@zettel/core](https://www.npmjs.com/package/@zettel/core/v/${{ steps.changelog_entry.outputs.version }})
            - [@zettel/react](https://www.npmjs.com/package/@zettel/react/v/${{ steps.changelog_entry.outputs.version }})
          draft: false
          prerelease: false
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/build

