on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install changelog parser
        run: yarn
      - name: Get Changelog Entry
        id: changelog_entry
        run: node scripts/release.js
      - name: Assert Package Versions
        run: node scripts/assert-package-version.js
        with:
          version: ${{ steps.changelog_entry.outputs.version }}
          packages: core, react
#      - name: Print the entry
#        run: |
#          echo "${{ steps.changelog_entry.outputs.title }}"
#          echo "${{ steps.changelog_entry.outputs.version }}"
#          echo "${{ steps.changelog_entry.outputs.description }}"

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: ${{ steps.changelog_reader.outputs.log_entry }} # This pulls from the GET CHANGELOG ENTRY step above, referencing it's ID to get its outputs object, which include a `log_entry`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          draft: false
#          prerelease: false